# Generated by Django 3.2.13 on 2022-11-11 00:30

from django.db import migrations, models
import imagekit.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('unit', models.CharField(max_length=64)),
                ('weight', models.CharField(max_length=64)),
                ('produt_thum_img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('produt_detail_img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('produt_desc_img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField()),
                ('sales_rate', models.PositiveIntegerField()),
                ('allergy', multiselectfield.db.fields.MultiSelectField(choices=[('고등어', '고등어'), ('땅콩', '땅콩'), ('토마토', '토마토'), ('닭고기', '닭고기'), ('새우', '새우'), ('복숭아', '복숭아'), ('난류', '난류'), ('쇠고기', '쇠고기'), ('조개류', '조개류'), ('오징어', '오징어'), ('밀', '밀'), ('아황산류', '아황산류'), ('우유', '우유'), ('게', '게'), ('메밀', '메밀'), ('호두', '호두'), ('대두', '대두'), ('돼지고기', '돼지고기')], max_length=62)),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': '상품',
            },
        ),
    ]
